server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: blog_path_route
          uri: http://localhost:7010
          predicates:
            - Path=/api/blog
